apiVersion: v1
data:
    api-token: ENC[AES256_GCM,data:a0Trg6rMt185xQPkCMx9XO/lADGWkGIgS/KjSZL84XbpcSdHcIZI1Ur23XDRXkKuCRFFA7STGVgRcHyf8W5xt12wM6uKKuxm,iv:6XWYvw8fwzJEmrTib+U34Eux/5enhZpLiGouh0KAfAQ=,tag:Ndm1N5ktgxGnOl3rbqmLIg==,type:str]
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bkRybEdldEJxUXg0aGZE
            QXZIRG90RkdoeHFMRFVFM2NBT3NDOGhGTDJRCldJYVJRYm9ETXhzcGx0c1lWYWtl
            MDdlVStJbmNOa3RiRTFvWU5lNDR5WVUKLS0tIEc4blZMcEpkeERxeGxuSzhWMlV4
            emhnKzNZM3lrbUo0VXIybHFraGhuZUEKj7MSxa/qba2PAQWgpXG27Z7W4S/psy0u
            JB5zOSgkytx+fopwRB+3Y3mRQV4bEEtRKZicIV7Egz/Qq2bz9JQg0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12rrefewrwf5rals9tapqdjjjysxa3t8rvzq04kwur0pyq9wsvs9q6eel2m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-26T02:51:01Z"
    mac: ENC[AES256_GCM,data:qdNN3i1Gvmqc9dQnsCCz6/apje7iQjawhuVXp/HoIcM+UyEw9ySFdfhqiPa7ao1ZPdXHaN4JUML0/2N/ESAGoMnqQtxbaUTu4dYhGMiR+JCc6Oda2ya6db0kZx2zZauzql+bTVSn0FX7f1mUxavW7UyhJtXPCglIny1cbVyucCQ=,iv:3hz9OP9bSa3hBt1ZoggEMIWOEyiepTgXldg7H9RMyv4=,tag:PtzOcPSm7aqan+IcO4UIYg==,type:str]
    version: 3.13.3
