apiVersion: v1
data:
    creds.json: ENC[AES256_GCM,data:XPOnVENGDDqrqLNN27g3mtcxdCv4QHokOkK5AOkuBk4vIVFyAOGnxd/shCZkAPYWBuZ0dNF1nSMp7SvLbsE3KNibta4DwL+aZwVoZtE1H4bK8BuGoq97V4aKZT2WX4hTKimE26c3MUw+bida+vfaJEdSSYTp43vyhZzY4TWF7qZyxLTJEGrvfVGNIlFPZ3XkmUFSNCgP7u7vMPt7e6ps5ihKDdVEUHrMH/tdopYwbjcTm4EVqT3uc7JhpW4GBjmENTmecH7ScW9OGWmH8Kq9TqHlUPZ4rvNsXtx677YkoQyQgSs0Xg2uAOU3A98=,iv:hdMZZb/fDU1k1JP82NlLbwa/yhOfUxeGZ9t1xti7Pcw=,tag:fq9ZOV7eovzJ1mkS+JDb1w==,type:str]
kind: Secret
metadata:
    name: tunnel-creds
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVU9Xa3I2SDAvZDdPK3hY
            K0hJdWZYaHN3TnROd055Q200ME56VDlGaGtjCno0TVI3VGdWeWV2LzNKWnAwOXho
            K2ZsK3d2K0E1TnUwQUJkZWVFbE1ram8KLS0tIDBWM3JIdG5Xckt5T0tvWDZwTnE0
            UklyMXBhREVZdVVvV2xLUkRnWlZaMWMKiabHd+P+unCrvjdy1ClT55L3Ja9XrQPR
            B9A6//JkvSL8pn6W/OCyk6pS1qdQpe5jrfM+hBE9xR7g45PjGyr4eQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12rrefewrwf5rals9tapqdjjjysxa3t8rvzq04kwur0pyq9wsvs9q6eel2m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T21:53:39Z"
    mac: ENC[AES256_GCM,data:BHWjB+vo3VedZXwbMmsbWbWS+NtczOkL1OLtfBbeOH8wxOiI2rd30xSFMX/EkUm9/YMCecxvzjeq5mdhWBwTsRr0zcMwQu/txzpVO6HVCk1KEC9gmjDGhnrL7biWOL7xKVcqFdIWaaEBe81RUacwO4XPgaOfFbKqdbiZfby2S/M=,iv:lVXr/F4EMb0QDtrpDJgJPMkjfpJln4PkukIR4wqhh08=,tag:Apzj9FQRRoU7TXJtBY//wg==,type:str]
    version: 3.13.3
