apiVersion: apps/v1
kind: deployment
metadata:
  name: linkding
spec:
  replica: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
    containers:
      - name: linkding
        image: sissbruecker/linkding:1.31.0
        ports:
          - containerPort: 9090
